name: OpenWrt Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone ImmortalWrt repository
        run: git clone https://github.com/immortalwrt/immortalwrt.git

      - name: Copy .config file
        run: |
          ls 
          cp config immortalwrt/.config

      - name: Replace feeds.conf.default
        run: cp feeds.conf.default immortalwrt/feeds.conf.default

      - name: Set up build environment
        run: sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'

      - name: Modify config_generate file
        run: | 
          cd immortalwrt
          sed -i 's/192.168.1.1/192.168.8.1/g' immortalwrt/package/base-files/files/bin/config_generate

      - name: Update and install feeds
        run: |
          cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Download package sources
        run: |
          cd immortalwrt
          make download -j8

      - name: Compile OpenWrt
        run: |
          cd immortalwrt
          make V=s -j$(nproc)

      - name: Compress and package binaries
        run: zip -r bin.zip immortalwrt/bin

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt Binaries
          path: bin.zip
